### ISSUE TITLE
Integration no longer working with HA 2023.06

### ISSUE THREAD

**Issue by Kurisutian** [rgc99/irrigation_unlimited#116]
**Describe the bug**
After the update to HA 2023.06 the integration can no longer be loaded.

**To Reproduce**
1. Upgrade HA to 2023.06
2. Check Notifications after a couple of seconds

**Expected behavior**
Integration loads and is fully functional.

**Additional context**
The following errors are in the logs:

```
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: homeassistant.loader
Source: custom_components/smart_irrigation/sensor.py:124
Integration: Smart Irrigation (documentation, issues)
First occurred: 21:25:58 (2 occurrences)
Last logged: 21:25:58

Unexpected exception importing platform custom_components.smart_irrigation.sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 833, in get_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 850, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/smart_irrigation/sensor.py", line 102, in <module>
    class SmartIrrigationSensor(SmartIrrigationEntity):
  File "/config/custom_components/smart_irrigation/sensor.py", line 124, in SmartIrrigationSensor
    @asyncio.coroutine
     ^^^^^^^^^^^^^^^^^
AttributeError: module 'asyncio' has no attribute 'coroutine'

```

and 

```
Logger: homeassistant.setup
Source: setup.py:374
First occurred: 21:25:58 (2 occurrences)
Last logged: 21:25:58

Unable to prepare setup for platform smart_irrigation.sensor: Platform not found (Exception importing custom_components.smart_irrigation.sensor).
```

**Comment by rgc99** [comment]
This issue is not related to this integration. You can find more information about this [here](https://github.com/jeroenterheerdt/HAsmartirrigation/issues/130)

**Comment by Kurisutian** [comment]
Sorry that I have not checked for this being reported before. Should have done that. Thanks for the hint!
