### ISSUE TITLE
Templating error in service call manual_run

### ISSUE THREAD

**Issue by evercape** [rgc99/irrigation_unlimited#152]
**Describe the bug**
I want to create multiple buttons to trigger individual runs of zones, instead of using the drop down version of the [individual run card](https://github.com/rgc99/irrigation_unlimited#84-manual-run-card). The duration in minutes is handled via a helper entity `input_number.irrigation_runtime_in_minutes`.

I have created two possible solutions:

1. script with service call `manual_run` --> this is working
2. button with `tap_action` and then trigger service call `manual_run` --> this is not working and produces an error

**To Reproduce**

1. create helper entity `input_number.irrigation_runtime_in_minutes` I made it a slider and set min=1, max=60
2. create script (see below)
3. create dashboard cards (see below)

```
alias: test_irrigation
sequence:
  - service: irrigation_unlimited.manual_run
    data:
      entity_id: binary_sensor.irrigation_unlimited_c1_z1
      time:
        hours: 0
        minutes: '{{ states(''input_number.irrigation_runtime_in_minutes'') | int }}'
        seconds: 0
mode: single

```

```
cards:
      - type: entities
        entities:
          - entity: input_number.irrigation_runtime_in_minutes
            name: Run manual in minutes
            icon: mdi:timer-sand
          - entity: script.test_irrigation
      - show_name: false
        show_icon: true
        type: button
        tap_action:
          action: call-service
          service: irrigation_unlimited.manual_run
          data:
            entity_id: binary_sensor.irrigation_unlimited_c1_z1
            time:
              hours: 0
              minutes: '{{ states(''input_number.irrigation_runtime_in_minutes'') | int }}'
              seconds: 0
      - type: custom:button-card
        icon: mdi:timer-sand
        tap_action:
          action: call-service
          service: irrigation_unlimited.manual_run
          data:
            entity_id: binary_sensor.irrigation_unlimited_c1_z1
            time:
              hours: 0
              minutes: '{{ states(''input_number.irrigation_runtime_in_minutes'') | int }}'
              seconds: 0
      - type: custom:mushroom-entity-card
        entity: binary_sensor.irrigation_unlimited_c1_z1
        tap_action:
          action: call-service
          service: irrigation_unlimited.manual_run
          data:
            entity_id: binary_sensor.irrigation_unlimited_c1_z1
            time:
              hours: 0
              minutes: '{{ states(''input_number.irrigation_runtime_in_minutes'') | int }}'
              seconds: 0
      - type: custom:mushroom-entity-card
        entity: person.martin
        tap_action:
          action: call-service
          service: notify.mobile_app_martins_iphone_14_pro
          target: {}
          data:
            title: title
            message: >-
              test {{ states('input_number.irrigation_runtime_in_minutes') | int
              }}
```

**Expected behavior**
The execution of the script works, the irrigation zone starts.

Any of the buttons (normal button card, custom button, mushroom button card) trigger an error. I created another mushroom card to send the `input_number.irrigation_runtime_in_minutes` as message to my phone which works.

Unless I am missing something it appears that the templating does not 100% work (it does via script, but not via button).

**Screenshots**
![Martin_Testing_–_Home_Assistant](https://github.com/rgc99/irrigation_unlimited/assets/4627761/57b7f849-2fc0-4515-b3b8-e4f1acc4e013)

Logs:
```
Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/commands.py:230
Integration: Home Assistant WebSocket API ([documentation](https://www.home-assistant.io/integrations/websocket_api), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
First occurred: 8:25:41 AM (13 occurrences)
Last logged: 9:03:25 AM

[140370018049088] 'dict' object has no attribute 'total_seconds'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 230, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 2035, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2072, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 830, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 876, in entity_service_call
    response_data = await _handle_entity_call(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 948, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/irrigation_unlimited/service.py", line 39, in async_entity_service_handler
    entity.dispatch(call.service, call)
  File "/config/custom_components/irrigation_unlimited/entity.py", line 288, in dispatch
    self._coordinator.service_call(service, self._controller, self._zone, call.data)
  File "/config/custom_components/irrigation_unlimited/irrigation_unlimited.py", line 5424, in service_call
    zone.service_manual_run(data1, stime)
  File "/config/custom_components/irrigation_unlimited/irrigation_unlimited.py", line 1880, in service_manual_run
    duration = wash_td(data.get(CONF_TIME))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/irrigation_unlimited/irrigation_unlimited.py", line 249, in wash_td
    whole_seconds = int(delta.total_seconds())
                        ^^^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'total_seconds'
```

Thanks a lot,
Martin

**Comment by rgc99** [comment]
Probably the best way to track this down is to compare the log entries between the two. You should see a line like below in the  log file
```yaml
2023-11-23 07:20:17.330 INFO (MainThread) [custom_components.irrigation_unlimited] CALL [2023-11-23 07:20:17] service: manual_run, controller: 1, zone: 8, data: {"entity_id": ["binary_sensor.irrigation_unlimited_c1_z8"], "time": "0:01:00"}
```
The part to carefully look at is the `data:` section. There will be some difference.

**Comment by evercape** [comment]
Thanks for helping out.

I am adding logs with some comments from my side:

```
2023-11-23 11:20:29.819 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration irrigation_unlimited which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-11-23 11:20:29.819 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration pyscript which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-11-23 11:20:29.819 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-11-23 11:20:32.458 INFO (MainThread) [custom_components.irrigation_unlimited] 
-------------------------------------------------------------------
Irrigation Unlimited
Version: 2023.11.0
If you have any issues with this you need to open an issue here:
https://github.com/rgc99/irrigation_unlimited/issues
-------------------------------------------------------------------

2023-11-23 11:20:32.458 DEBUG (MainThread) [custom_components.irrigation_unlimited] LOAD
2023-11-23 11:20:32.489 DEBUG (MainThread) [custom_components.irrigation_unlimited] REGISTER [2023-11-23 11:20:32] controller: 0, zone: 0, entity: irrigation_unlimited.coordinator
2023-11-23 11:20:32.489 DEBUG (MainThread) [custom_components.irrigation_unlimited] CALL [2023-11-23 11:20:32] service: enable, controller: 1, zone: 0, data: {}
2023-11-23 11:20:32.489 DEBUG (MainThread) [custom_components.irrigation_unlimited] CALL [2023-11-23 11:20:32] service: suspend, controller: 1, zone: 0, data: {"reset": null}
2023-11-23 11:20:32.489 DEBUG (MainThread) [custom_components.irrigation_unlimited] CALL [2023-11-23 11:20:32] service: enable, controller: 1, zone: 0, data: {"sequence_id": 1}
2023-11-23 11:20:32.489 DEBUG (MainThread) [custom_components.irrigation_unlimited] CALL [2023-11-23 11:20:32] service: suspend, controller: 1, zone: 0, data: {"reset": null, "sequence_id": 1}
2023-11-23 11:20:32.489 DEBUG (MainThread) [custom_components.irrigation_unlimited] CALL [2023-11-23 11:20:32] service: adjust_time, controller: 1, zone: 0, data: {"reset": null, "sequence_id": 1}
2023-11-23 11:20:32.490 DEBUG (MainThread) [custom_components.irrigation_unlimited] CALL [2023-11-23 11:20:32] service: enable, controller: 1, zone: 0, data: {"sequence_id": 1, "zones": [1]}
2023-11-23 11:20:32.490 DEBUG (MainThread) [custom_components.irrigation_unlimited] CALL [2023-11-23 11:20:32] service: suspend, controller: 1, zone: 0, data: {"reset": null, "sequence_id": 1, "zones": [1]}
2023-11-23 11:20:32.490 DEBUG (MainThread) [custom_components.irrigation_unlimited] CALL [2023-11-23 11:20:32] service: adjust_time, controller: 1, zone: 0, data: {"reset": null, "sequence_id": 1, "zones": [1]}
2023-11-23 11:20:32.490 DEBUG (MainThread) [custom_components.irrigation_unlimited] CALL [2023-11-23 11:20:32] service: enable, controller: 1, zone: 0, data: {"sequence_id": 1, "zones": [2]}
2023-11-23 11:20:32.490 DEBUG (MainThread) [custom_components.irrigation_unlimited] CALL [2023-11-23 11:20:32] service: suspend, controller: 1, zone: 0, data: {"reset": null, "sequence_id": 1, "zones": [2]}
2023-11-23 11:20:32.490 DEBUG (MainThread) [custom_components.irrigation_unlimited] CALL [2023-11-23 11:20:32] service: adjust_time, controller: 1, zone: 0, data: {"reset": null, "sequence_id": 1, "zones": [2]}
2023-11-23 11:20:32.490 DEBUG (MainThread) [custom_components.irrigation_unlimited] CALL [2023-11-23 11:20:32] service: enable, controller: 1, zone: 0, data: {"sequence_id": 1, "zones": [3]}
2023-11-23 11:20:32.490 DEBUG (MainThread) [custom_components.irrigation_unlimited] CALL [2023-11-23 11:20:32] service: suspend, controller: 1, zone: 0, data: {"reset": null, "sequence_id": 1, "zones": [3]}
2023-11-23 11:20:32.490 DEBUG (MainThread) [custom_components.irrigation_unlimited] CALL [2023-11-23 11:20:32] service: adjust_time, controller: 1, zone: 0, data: {"reset": null, "sequence_id": 1, "zones": [3]}
2023-11-23 11:20:32.490 DEBUG (MainThread) [custom_components.irrigation_unlimited] CALL [2023-11-23 11:20:32] service: enable, controller: 1, zone: 0, data: {"sequence_id": 2}
2023-11-23 11:20:32.490 DEBUG (MainThread) [custom_components.irrigation_unlimited] CALL [2023-11-23 11:20:32] service: suspend, controller: 1, zone: 0, data: {"reset": null, "sequence_id": 2}
2023-11-23 11:20:32.490 DEBUG (MainThread) [custom_components.irrigation_unlimited] CALL [2023-11-23 11:20:32] service: adjust_time, controller: 1, zone: 0, data: {"reset": null, "sequence_id": 2}
2023-11-23 11:20:32.490 DEBUG (MainThread) [custom_components.irrigation_unlimited] CALL [2023-11-23 11:20:32] service: enable, controller: 1, zone: 0, data: {"sequence_id": 2, "zones": [1]}
2023-11-23 11:20:32.490 DEBUG (MainThread) [custom_components.irrigation_unlimited] CALL [2023-11-23 11:20:32] service: suspend, controller: 1, zone: 0, data: {"reset": null, "sequence_id": 2, "zones": [1]}
2023-11-23 11:20:32.490 DEBUG (MainThread) [custom_components.irrigation_unlimited] CALL [2023-11-23 11:20:32] service: adjust_time, controller: 1, zone: 0, data: {"reset": null, "sequence_id": 2, "zones": [1]}
2023-11-23 11:20:32.490 DEBUG (MainThread) [custom_components.irrigation_unlimited] CALL [2023-11-23 11:20:32] service: enable, controller: 1, zone: 0, data: {"sequence_id": 2, "zones": [2]}
2023-11-23 11:20:32.490 DEBUG (MainThread) [custom_components.irrigation_unlimited] CALL [2023-11-23 11:20:32] service: suspend, controller: 1, zone: 0, data: {"reset": null, "sequence_id": 2, "zones": [2]}
2023-11-23 11:20:32.490 DEBUG (MainThread) [custom_components.irrigation_unlimited] CALL [2023-11-23 11:20:32] service: adjust_time, controller: 1, zone: 0, data: {"reset": null, "sequence_id": 2, "zones": [2]}
2023-11-23 11:20:32.490 DEBUG (MainThread) [custom_components.irrigation_unlimited] CALL [2023-11-23 11:20:32] service: enable, controller: 1, zone: 0, data: {"sequence_id": 2, "zones": [3]}
2023-11-23 11:20:32.490 DEBUG (MainThread) [custom_components.irrigation_unlimited] CALL [2023-11-23 11:20:32] service: suspend, controller: 1, zone: 0, data: {"reset": null, "sequence_id": 2, "zones": [3]}
2023-11-23 11:20:32.490 DEBUG (MainThread) [custom_components.irrigation_unlimited] CALL [2023-11-23 11:20:32] service: adjust_time, controller: 1, zone: 0, data: {"reset": null, "sequence_id": 2, "zones": [3]}
2023-11-23 11:20:32.490 DEBUG (MainThread) [custom_components.irrigation_unlimited] CALL [2023-11-23 11:20:32] service: enable, controller: 1, zone: 1, data: {}
2023-11-23 11:20:32.490 DEBUG (MainThread) [custom_components.irrigation_unlimited] CALL [2023-11-23 11:20:32] service: suspend, controller: 1, zone: 1, data: {"reset": null}
2023-11-23 11:20:32.490 DEBUG (MainThread) [custom_components.irrigation_unlimited] CALL [2023-11-23 11:20:32] service: adjust_time, controller: 1, zone: 1, data: {"reset": null}
2023-11-23 11:20:32.490 DEBUG (MainThread) [custom_components.irrigation_unlimited] CALL [2023-11-23 11:20:32] service: enable, controller: 1, zone: 2, data: {}
2023-11-23 11:20:32.490 DEBUG (MainThread) [custom_components.irrigation_unlimited] CALL [2023-11-23 11:20:32] service: suspend, controller: 1, zone: 2, data: {"reset": null}
2023-11-23 11:20:32.490 DEBUG (MainThread) [custom_components.irrigation_unlimited] CALL [2023-11-23 11:20:32] service: adjust_time, controller: 1, zone: 2, data: {"reset": null}
2023-11-23 11:20:32.490 DEBUG (MainThread) [custom_components.irrigation_unlimited] CALL [2023-11-23 11:20:32] service: enable, controller: 1, zone: 3, data: {}
2023-11-23 11:20:32.490 DEBUG (MainThread) [custom_components.irrigation_unlimited] CALL [2023-11-23 11:20:32] service: suspend, controller: 1, zone: 3, data: {"reset": null}
2023-11-23 11:20:32.490 DEBUG (MainThread) [custom_components.irrigation_unlimited] CALL [2023-11-23 11:20:32] service: adjust_time, controller: 1, zone: 3, data: {"reset": null}
2023-11-23 11:20:32.490 DEBUG (MainThread) [custom_components.irrigation_unlimited] CALL [2023-11-23 11:20:32] service: enable, controller: 1, zone: 4, data: {}
2023-11-23 11:20:32.490 DEBUG (MainThread) [custom_components.irrigation_unlimited] CALL [2023-11-23 11:20:32] service: suspend, controller: 1, zone: 4, data: {"reset": null}
2023-11-23 11:20:32.490 DEBUG (MainThread) [custom_components.irrigation_unlimited] CALL [2023-11-23 11:20:32] service: adjust_time, controller: 1, zone: 4, data: {"reset": null}
2023-11-23 11:20:32.490 DEBUG (MainThread) [custom_components.irrigation_unlimited] CALL [2023-11-23 11:20:32] service: enable, controller: 1, zone: 5, data: {}
2023-11-23 11:20:32.490 DEBUG (MainThread) [custom_components.irrigation_unlimited] CALL [2023-11-23 11:20:32] service: suspend, controller: 1, zone: 5, data: {"reset": null}
2023-11-23 11:20:32.490 DEBUG (MainThread) [custom_components.irrigation_unlimited] CALL [2023-11-23 11:20:32] service: adjust_time, controller: 1, zone: 5, data: {"reset": null}
2023-11-23 11:20:32.490 DEBUG (MainThread) [custom_components.irrigation_unlimited] CALL [2023-11-23 11:20:32] service: enable, controller: 1, zone: 6, data: {}
2023-11-23 11:20:32.490 DEBUG (MainThread) [custom_components.irrigation_unlimited] CALL [2023-11-23 11:20:32] service: suspend, controller: 1, zone: 6, data: {"reset": null}
2023-11-23 11:20:32.490 DEBUG (MainThread) [custom_components.irrigation_unlimited] CALL [2023-11-23 11:20:32] service: adjust_time, controller: 1, zone: 6, data: {"reset": null}
2023-11-23 11:20:32.541 DEBUG (MainThread) [custom_components.irrigation_unlimited] START
2023-11-23 11:20:33.977 DEBUG (MainThread) [custom_components.irrigation_unlimited] REGISTER [2023-11-23 11:20:33] controller: 1, zone: 0, entity: binary_sensor.irrigation_unlimited_c1_m
2023-11-23 11:20:33.977 DEBUG (MainThread) [custom_components.irrigation_unlimited] REGISTER [2023-11-23 11:20:33] controller: 1, zone: 1, entity: binary_sensor.irrigation_unlimited_c1_z1
2023-11-23 11:20:33.978 DEBUG (MainThread) [custom_components.irrigation_unlimited] REGISTER [2023-11-23 11:20:33] controller: 1, zone: 2, entity: binary_sensor.irrigation_unlimited_c1_z2
2023-11-23 11:20:33.978 DEBUG (MainThread) [custom_components.irrigation_unlimited] REGISTER [2023-11-23 11:20:33] controller: 1, zone: 3, entity: binary_sensor.irrigation_unlimited_c1_z3
2023-11-23 11:20:33.978 DEBUG (MainThread) [custom_components.irrigation_unlimited] REGISTER [2023-11-23 11:20:33] controller: 1, zone: 4, entity: binary_sensor.irrigation_unlimited_c1_z4
2023-11-23 11:20:33.978 DEBUG (MainThread) [custom_components.irrigation_unlimited] REGISTER [2023-11-23 11:20:33] controller: 1, zone: 5, entity: binary_sensor.irrigation_unlimited_c1_z5
2023-11-23 11:20:33.978 DEBUG (MainThread) [custom_components.irrigation_unlimited] REGISTER [2023-11-23 11:20:33] controller: 1, zone: 6, entity: binary_sensor.irrigation_unlimited_c1_z6
2023-11-23 11:20:42.542 DEBUG (MainThread) [custom_components.irrigation_unlimited] INITIALISED

Comment: 
The following error occurs when I trigger the manual run via a button. I had set the irrigation_runtime_in_minutes to 1

type: button
tap_action:
  action: call-service
  service: irrigation_unlimited.manual_run
  data:
    entity_id: binary_sensor.irrigation_unlimited_c1_z6
    time:
      hours: 0
      minutes: '{{ states(''input_number.irrigation_runtime_in_minutes'') | int }}'
      seconds: 0

2023-11-23 11:25:22.962 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140491464503232] 'dict' object has no attribute 'total_seconds'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 230, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 2035, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2072, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 830, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 876, in entity_service_call
    response_data = await _handle_entity_call(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 948, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/irrigation_unlimited/service.py", line 39, in async_entity_service_handler
    entity.dispatch(call.service, call)
  File "/config/custom_components/irrigation_unlimited/entity.py", line 288, in dispatch
    self._coordinator.service_call(service, self._controller, self._zone, call.data)
  File "/config/custom_components/irrigation_unlimited/irrigation_unlimited.py", line 5424, in service_call
    zone.service_manual_run(data1, stime)
  File "/config/custom_components/irrigation_unlimited/irrigation_unlimited.py", line 1880, in service_manual_run
    duration = wash_td(data.get(CONF_TIME))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/irrigation_unlimited/irrigation_unlimited.py", line 249, in wash_td
    whole_seconds = int(delta.total_seconds())
                        ^^^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'total_seconds'

Comment: 
The following error occurs when I trigger the manual run via a button. I had set the irrigation_runtime_in_minutes to 6

type: button
tap_action:
  action: call-service
  service: irrigation_unlimited.manual_run
  data:
    entity_id: binary_sensor.irrigation_unlimited_c1_z6
    time:
      hours: 0
      minutes: '{{ states(''input_number.irrigation_runtime_in_minutes'') | int }}'
      seconds: 0


2023-11-23 11:25:26.609 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140491464503232] 'dict' object has no attribute 'total_seconds'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 230, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 2035, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2072, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 830, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 876, in entity_service_call
    response_data = await _handle_entity_call(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 948, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/irrigation_unlimited/service.py", line 39, in async_entity_service_handler
    entity.dispatch(call.service, call)
  File "/config/custom_components/irrigation_unlimited/entity.py", line 288, in dispatch
    self._coordinator.service_call(service, self._controller, self._zone, call.data)
  File "/config/custom_components/irrigation_unlimited/irrigation_unlimited.py", line 5424, in service_call
    zone.service_manual_run(data1, stime)
  File "/config/custom_components/irrigation_unlimited/irrigation_unlimited.py", line 1880, in service_manual_run
    duration = wash_td(data.get(CONF_TIME))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/irrigation_unlimited/irrigation_unlimited.py", line 249, in wash_td
    whole_seconds = int(delta.total_seconds())
                        ^^^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'total_seconds'


Comment: 
The following inf logger occurs when I trigger the manual run via a script in entity card. I had set the irrigation_runtime_in_minutes to 13:
alias: test_irrigation
sequence:
  - service: irrigation_unlimited.manual_run
    data:
      entity_id: binary_sensor.irrigation_unlimited_c1_z6
      time:
        hours: 0
        minutes: "{{ states('input_number.irrigation_runtime_in_minutes') | int }}"
        seconds: 0
mode: single



2023-11-23 11:25:41.328 INFO (MainThread) [custom_components.irrigation_unlimited] CALL [2023-11-23 11:25:41] service: manual_run, controller: 1, zone: 6, data: {"entity_id": ["binary_sensor.irrigation_unlimited_c1_z6"], "time": "0:13:00"}
2023-11-23 11:25:42.002 INFO (MainThread) [custom_components.irrigation_unlimited] EVENT [2023-11-23 11:25:42] controller: 1, zone: 0, state: 1
2023-11-23 11:25:42.002 INFO (MainThread) [custom_components.irrigation_unlimited] EVENT [2023-11-23 11:25:42] controller: 1, zone: 6, state: 1, data: 6.0.0.0.0
2023-11-23 11:25:46.641 INFO (MainThread) [custom_components.irrigation_unlimited] CALL [2023-11-23 11:25:46] service: cancel, controller: 1, zone: 6, data: {"entity_id": ["binary_sensor.irrigation_unlimited_c1_z6"]}
2023-11-23 11:25:46.643 INFO (MainThread) [custom_components.irrigation_unlimited] EVENT [2023-11-23 11:25:46] controller: 1, zone: 6, state: 0
2023-11-23 11:25:46.643 INFO (MainThread) [custom_components.irrigation_unlimited] EVENT [2023-11-23 11:25:46] controller: 1, zone: 0, state: 0

Comment: I have then cancelled the manual run time via the companian card

2023-11-23 11:25:46.676 INFO (MainThread) [custom_components.irrigation_unlimited] CALL [2023-11-23 11:25:46] service: cancel, controller: 1, zone: 6, data: {"entity_id": ["binary_sensor.irrigation_unlimited_c1_z6"]}



Comment: 
The following error occurs when I trigger the manual run via a button. I had set the irrigation_runtime_in_minutes to 19

type: button
tap_action:
  action: call-service
  service: irrigation_unlimited.manual_run
  data:
    entity_id: binary_sensor.irrigation_unlimited_c1_z6
    time:
      hours: 0
      minutes: '{{ states(''input_number.irrigation_runtime_in_minutes'') | int }}'
      seconds: 0

2023-11-23 11:25:51.790 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140491464503232] 'dict' object has no attribute 'total_seconds'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 230, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 2035, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2072, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 830, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 876, in entity_service_call
    response_data = await _handle_entity_call(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 948, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/irrigation_unlimited/service.py", line 39, in async_entity_service_handler
    entity.dispatch(call.service, call)
  File "/config/custom_components/irrigation_unlimited/entity.py", line 288, in dispatch
    self._coordinator.service_call(service, self._controller, self._zone, call.data)
  File "/config/custom_components/irrigation_unlimited/irrigation_unlimited.py", line 5424, in service_call
    zone.service_manual_run(data1, stime)
  File "/config/custom_components/irrigation_unlimited/irrigation_unlimited.py", line 1880, in service_manual_run
    duration = wash_td(data.get(CONF_TIME))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/irrigation_unlimited/irrigation_unlimited.py", line 249, in wash_td
    whole_seconds = int(delta.total_seconds())
                        ^^^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'total_seconds'
```

What appears to happen is that time in seconds is not calculated properly, maybe because the button does not pass the manual run time to your service call `manual_run`.

What I fail to understand is that it works well via script, and the actual value is being picked up via template in another test button:

```
type: custom:mushroom-entity-card
entity: person.martin_diessner
tap_action:
  action: call-service
  service: notify.mobile_app_martins_iphone_14_pro
  target: {}
  data:
    title: title
    message: test {{ states('input_number.irrigation_runtime_in_minutes') | int }}
```

Just really strange.

**Comment by rgc99** [comment]
I can reproduce this. Scripts fully process the data but the card only partially. I will look further into this but to make it work the `time:` must be passed on a single line. Here is one way by building a H:MM:SS string
```yaml
data:
  entity_id: binary_sensor.irrigation_unlimited_c1_z6
  time: "{{'0:' + states('input_number.irrigation_runtime_in_minutes') | int | string + ':00' }}"
```
Another possibility is to express the time in seconds. This one is a bit more elegant.
```yaml
data:
  entity_id: binary_sensor.irrigation_unlimited_c1_z6
  time: "{{states('input_number.irrigation_runtime_in_minutes') | int * 60 }}"
```

**Comment by evercape** [comment]
Thanks Robert, I agree the second possibility is the best.

A bit strange though that one trigger (script) works but the other (card) does not.

Your documentation with regards to [Duration/Time](https://github.com/rgc99/irrigation_unlimited#142-duration-time-period) is pretty clear that both `time` and/or any of `days/hour/minute/second` will work. On that note, is `days` in the example really correct? the schema template seems to only consider hour/minute/second, and as far as I understand the python code for conversion from string to time delta, days are not considered.

From my side this issue can be closed, as I ended up using a script where I pass parameter of entity and manual run time from the button.

This is how the card looks like for now:

![irrigation_unlimited_card](https://github.com/rgc99/irrigation_unlimited/assets/4627761/6d3e19dc-48c4-4840-aa7f-533d0cbd1898)


Thanks again for your help and for an amazing integration, a lot to learn from.
M

**Comment by rgc99** [comment]
Hi Martin,
What I found out. There are two parts to templating; compiling and rendering. The schema does the compiling and then it is rendered in the `service_call` section of the code. The issue was it did not do a deep or complex render as in the elements of a dict. It was just expected a simple string.

I suspect that the script compiles AND renders the template before passing it on. The card simply passes the data through and expects the receiver to make sense of it.

Looking at the [HA code](https://github.com/home-assistant/core/blob/b24fa4839db8a1e10d34d544ae6845838dc9c5f2/homeassistant/helpers/config_validation.py#L409) it seems `days:` is considered.

Cheers

**Comment by evercape** [comment]
Thanks Robert, much appreciated. Steep learning curve for me ;-)
