### ISSUE TITLE
The automation "Irrigation Unlimited Load UI Controls" (automation.irrigation_unlimited_load_ui_controls) has an action that calls an unknown service: irrigation_unlimited.list_config.

### ISSUE THREAD

**Issue by averkinderen** [rgc99/irrigation_unlimited#155]
## Configuration

```yaml

#################################################################
## Irrigiation
#################################################################
irrigation_unlimited:
  controllers:
    zones:
      - name: "Sprinkler Front House"
        entity_id: "switch.rain_bird_sprinkler_1"
      - name: "Sprinkler Back House"
        entity_id: "switch.rain_bird_sprinkler_2"
      - name: "Sprinkler Front Property"
        entity_id: "switch.rain_bird_sprinkler_3"   
      - name: "Sprinkler Side House"
        entity_id: "switch.rain_bird_sprinkler_4"
      - name: "Sprinkler Right Paddock"
        entity_id: "switch.rain_bird_sprinkler_5"
      - name: "Sprinkler Fire Hose"
        entity_id: "switch.rain_bird_sprinkler_6"
      - name: "Sprinkler Fire Break"
        entity_id: "switch.rain_bird_sprinkler_7"
      - name: "Sprinkler Middle Paddock"
        entity_id: "switch.rain_bird_sprinkler_8"
      - name: "Sprinkler Left Paddock"
        entity_id: "switch.rain_bird_sprinkler_9"
    sequences:
      - name: "Quick Soak"
        duration: "00:30"
        delay: "00:01"
        zones:
          - zone_id: 1
          - zone_id: 2
          - zone_id: 3
          - zone_id: 4

```

## Describe the bug
Getting the following error when I go to settings in HA

The automation "Irrigation Unlimited Load UI Controls" (automation.irrigation_unlimited_load_ui_controls) has an action that calls an unknown service: irrigation_unlimited.list_config.

![Screenshot 2023-12-21 112111](https://github.com/rgc99/irrigation_unlimited/assets/8144122/da740fb7-16f0-43ae-b0da-d6146addcaec)

## Debug log

These messages are very important in helping to determine the problem. Go into Settings -> System -> Logs. In the search box put in `irrigation_unlimited` (Note the underscore between the two words) and press the **LOAD FULL LOGS** button. Copy and paste below.

```text

2023-12-21 11:14:22.641 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration localtuya which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-12-21 11:14:22.643 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration average which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-12-21 11:14:22.645 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration iammeter_http which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-12-21 11:14:22.647 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration irrigation_unlimited which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-12-21 11:14:22.649 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration smart_irrigation which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-12-21 11:14:22.651 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration pyscript which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-12-21 11:14:22.652 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration dual_smart_thermostat which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-12-21 11:14:22.654 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration airtouch3 which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-12-21 11:14:22.658 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-12-21 11:14:22.662 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration alarmo which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-12-21 11:14:52.079 WARNING (MainThread) [custom_components.irrigation_unlimited] INCOMPLETE Cycle did not complete: controller: 1, zone: 4, sequence: 1, sequence_zone: 4
2023-12-21 11:14:53.781 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.iammeter_pf_a_2 (<class 'custom_components.iammeter_http.sensor.IammeterSensor'>) is using native unit of measurement '' which is not a valid unit for the device class ('power_factor') it is using; expected one of ['%', 'no unit of measurement']; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/lewei50/ha_iammeter/issues
2023-12-21 11:14:53.791 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.iammeter_pf_b_2 (<class 'custom_components.iammeter_http.sensor.IammeterSensor'>) is using native unit of measurement '' which is not a valid unit for the device class ('power_factor') it is using; expected one of ['%', 'no unit of measurement']; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/lewei50/ha_iammeter/issues
2023-12-21 11:14:53.796 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.iammeter_pf_c_2 (<class 'custom_components.iammeter_http.sensor.IammeterSensor'>) is using native unit of measurement '' which is not a valid unit for the device class ('power_factor') it is using; expected one of ['%', 'no unit of measurement']; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/lewei50/ha_iammeter/issues
2023-12-21 11:14:55.085 WARNING (MainThread) [homeassistant.helpers.entity] Updating state for sensor.solarnet_meter_mode (<class 'homeassistant.components.fronius.sensor.PowerFlowSensor'>) took 0.636 seconds. Please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+fronius%22
2023-12-21 11:14:56.434 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry My home for smartthings
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 402, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/smartthings/__init__.py", line 126, in async_setup_entry
    token = await api.generate_tokens(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pysmartthings/smartthings.py", line 209, in generate_tokens
    result = await self._service.generate_tokens(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pysmartthings/api.py", line 424, in generate_tokens
    raise APIInvalidGrant(data.get("error_description"))
pysmartthings.errors.APIInvalidGrant: Invalid refresh token: 94ce5451-e622-4386-9fd4-c1511fff9bf3 requested by clientId: 6ebcfab2-b032-465c-815f-cae34e5a2a28 with grantType: refresh_token, e.cause: no cause
2023-12-21 11:15:01.128 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2023-12-21 11:15:03.978 WARNING (MainThread) [homeassistant.components.media_player] Setup of media_player platform dlna_dmr is taking over 10 seconds.
2023-12-21 11:15:11.179 ERROR (MainThread) [homeassistant.components.template.template_entity] TemplateError('TypeError: bad operand type for unary -: 'list'') while processing template 'Template<template=({{ states('sensor.iammeter_importenergy_a_2') not in ['unknown','unavailable'] and states('sensor.iammeter_importenergy_b_2') not in ['unknown','unavailable'] and states('sensor.iammeter_importenergy_c_2') not in - ['unknown','unavailable'] }}) renders=4>' for attribute '_attr_available' in entity 'sensor.energy_total'
2023-12-21 11:15:11.260 ERROR (MainThread) [custom_components.average.sensor] Unable to find an entity "sensor.wupws_preciptotal"
2023-12-21 11:15:11.262 ERROR (MainThread) [custom_components.average.sensor] Unable to find an entity "sensor.wupws_preciptotal"
2023-12-21 11:15:11.264 ERROR (MainThread) [custom_components.average.sensor] Unable to find an entity "sensor.wupws_preciptotal"
2023-12-21 11:15:11.268 ERROR (MainThread) [custom_components.average.sensor] Unable to find an entity "sensor.wupws_preciptotal"
2023-12-21 11:15:11.270 ERROR (MainThread) [custom_components.average.sensor] Unable to find an entity "sensor.wupws_preciptotal"
2023-12-21 11:15:11.276 ERROR (MainThread) [custom_components.average.sensor] Unable to find an entity "sensor.wupws_temp"
2023-12-21 11:15:11.278 ERROR (MainThread) [custom_components.average.sensor] Unable to find an entity "sensor.wupws_temp"
2023-12-21 11:15:11.280 ERROR (MainThread) [custom_components.average.sensor] Unable to find an entity "sensor.wupws_temp"
2023-12-21 11:15:11.282 ERROR (MainThread) [custom_components.average.sensor] Unable to find an entity "sensor.wupws_temp"
2023-12-21 11:15:11.284 ERROR (MainThread) [custom_components.average.sensor] Unable to find an entity "sensor.wupws_temp"
2023-12-21 11:15:11.286 ERROR (MainThread) [custom_components.average.sensor] Unable to find an entity "sensor.wupws_temp"
2023-12-21 11:15:11.287 ERROR (MainThread) [custom_components.average.sensor] Unable to find an entity "sensor.plaid_systems_ps_sprzms_slp3_temperature"
2023-12-21 11:15:11.592 ERROR (MainThread) [homeassistant.components.automation.irrigation_unlimited_load_ui_controls] Irrigation Unlimited Load UI Controls: Error executing script. Service not found for call_service at pos 1: Service irrigation_unlimited.list_config not found.
2023-12-21 11:15:12.348 WARNING (MainThread) [custom_components.irrigation_unlimited] SYNCHRONISATION [2023-12-21 11:15:12] Switch does not match current state: expected: off, switch: switch.rain_bird_sprinkler_1
2023-12-21 11:15:12.351 WARNING (MainThread) [custom_components.irrigation_unlimited] SYNCHRONISATION [2023-12-21 11:15:12] Switch does not match current state: expected: off, switch: switch.rain_bird_sprinkler_2
2023-12-21 11:15:12.352 WARNING (MainThread) [custom_components.irrigation_unlimited] SYNCHRONISATION [2023-12-21 11:15:12] Switch does not match current state: expected: off, switch: switch.rain_bird_sprinkler_3
2023-12-21 11:15:12.353 WARNING (MainThread) [custom_components.irrigation_unlimited] SYNCHRONISATION [2023-12-21 11:15:12] Switch does not match current state: expected: off, switch: switch.rain_bird_sprinkler_4
2023-12-21 11:15:12.354 WARNING (MainThread) [custom_components.irrigation_unlimited] SYNCHRONISATION [2023-12-21 11:15:12] Switch does not match current state: expected: off, switch: switch.rain_bird_sprinkler_5
2023-12-21 11:15:12.361 WARNING (MainThread) [custom_components.irrigation_unlimited] SYNCHRONISATION [2023-12-21 11:15:12] Switch does not match current state: expected: off, switch: switch.rain_bird_sprinkler_6
2023-12-21 11:15:12.362 WARNING (MainThread) [custom_components.irrigation_unlimited] SYNCHRONISATION [2023-12-21 11:15:12] Switch does not match current state: expected: off, switch: switch.rain_bird_sprinkler_7
2023-12-21 11:15:12.369 WARNING (MainThread) [custom_components.irrigation_unlimited] SYNCHRONISATION [2023-12-21 11:15:12] Switch does not match current state: expected: off, switch: switch.rain_bird_sprinkler_8
2023-12-21 11:15:12.375 WARNING (MainThread) [custom_components.irrigation_unlimited] SYNCHRONISATION [2023-12-21 11:15:12] Switch does not match current state: expected: off, switch: switch.rain_bird_sprinkler_9
2023-12-21 11:15:12.812 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities switch.rain_bird_sprinkler_1 are missing or not currently available
2023-12-21 11:15:12.812 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities switch.rain_bird_sprinkler_2 are missing or not currently available
2023-12-21 11:15:12.813 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities switch.rain_bird_sprinkler_3 are missing or not currently available
2023-12-21 11:15:12.813 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities switch.rain_bird_sprinkler_4 are missing or not currently available
2023-12-21 11:15:12.816 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities switch.rain_bird_sprinkler_5 are missing or not currently available
2023-12-21 11:15:12.817 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities switch.rain_bird_sprinkler_6 are missing or not currently available
2023-12-21 11:15:12.819 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities switch.rain_bird_sprinkler_7 are missing or not currently available
2023-12-21 11:15:12.819 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities switch.rain_bird_sprinkler_8 are missing or not currently available
2023-12-21 11:15:12.820 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities switch.rain_bird_sprinkler_9 are missing or not currently available
2023-12-21 11:15:15.440 WARNING (Recorder) [homeassistant.components.sensor.recorder] The unit of sensor.openweathermap_rain (mm/h) cannot be converted to the unit of previously compiled statistics (mm). Generation of long term statistics will be suppressed unless the unit changes back to mm or a compatible unit. Go to https://my.home-assistant.io/redirect/developer_statistics to fix this
2023-12-21 11:15:15.440 WARNING (Recorder) [homeassistant.components.sensor.recorder] The unit of sensor.openweathermap_snow (mm/h) cannot be converted to the unit of previously compiled statistics (mm). Generation of long term statistics will be suppressed unless the unit changes back to mm or a compatible unit. Go to https://my.home-assistant.io/redirect/developer_statistics to fix this
2023-12-21 11:21:17.078 WARNING (MainThread) [zigpy_deconz.uart] Lost connection: SerialException('device reports readiness to read but returned no data (device disconnected or multiple access on port?)')
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/serial_asyncio_fast/__init__.py", line 132, in _read_ready
    data = self._serial.read(self._max_read_size)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/serial/serialposix.py", line 595, in read
    raise SerialException(
serial.serialutil.SerialException: device reports readiness to read but returned no data (device disconnected or multiple access on port?)
2023-12-21 11:21:21.030 WARNING (MainThread) [zigpy_deconz.api] No response to 'CommandId.read_parameter' command with seq id '0x01'


```

**Comment by rgc99** [comment]
It would seem the [script](https://github.com/rgc99/irrigation_unlimited/blob/master/pyscript/irrigation_unlimited_service_shim.py) is not installed.

**Comment by Green2Matter** [comment]
I've started getting this error right after installing this script [https://github.com/rgc99/irrigation_unlimited/blob/master/pyscript/irrigation_unlimited_service_shim.py](url)

**Comment by rgc99** [comment]
Do you have [pyscript](https://github.com/custom-components/pyscript) installed?

**Comment by Green2Matter** [comment]
> Do you have [pyscript](https://github.com/custom-components/pyscript) installed?

Now it is, thanks 😆. But it wasn't clearly enough (for me) stated as dependancy...

**Comment by MojitoJoe1813** [comment]
Had the same issue: Wasn't clear enough that an or this integration need to be installed (and isn't per default). Maybe be more explicit in chapter 8.3 about that.

**Comment by ChrisX1809** [comment]
Got this error with Home Assistant 17.1 an can not solve because of missing pyscript support. What is the work around?
