### ISSUE TITLE
Unable to toggle controller/zone after upgrade to HA 2022.6

### ISSUE THREAD

**Issue by stomko11** [rgc99/irrigation_unlimited#75]
I noticed I am no longer able to disable zone/controller (nor enable or toggle) after upgrading to HA 2022.6 when calling the service, or when taping on the icon in the irrigation card.
Reverting back to 2022.5.5 - all is working as expected

**To Reproduce**
1) call appropriate service. Service seems to run OK (green check) yet no result. Zones are enabled (seem that way) yet don't show any active schedules

**Expected behavior**
Zone/controller should be disabled, or enabled and show next run time.

**Screenshots**
![image](https://user-images.githubusercontent.com/88718231/171632548-6ea8328d-704a-494a-9144-3a05a6ec481a.png)

**Desktop (please complete the following information):**
 - OS: 2022.6

**Additional context**
Following logs are observed in HA:

```
Logger: homeassistant
Source: util/async_.py:168
First occurred: 2:37:09 PM (78 occurrences)
Last logged: 2:43:19 PM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/irrigation_unlimited/irrigation_unlimited.py", line 3986, in _async_timer
    self.timer(atime)
  File "/config/custom_components/irrigation_unlimited/irrigation_unlimited.py", line 3982, in timer
    self.poll_main(atime)
  File "/config/custom_components/irrigation_unlimited/irrigation_unlimited.py", line 3969, in poll_main
    self.poll(atime, force)
  File "/config/custom_components/irrigation_unlimited/irrigation_unlimited.py", line 3957, in poll
    if self.muster(wtime, force) != 0:
  File "/config/custom_components/irrigation_unlimited/irrigation_unlimited.py", line 3915, in muster
    self._history.muster(stime, entity_ids, force)
  File "/config/custom_components/irrigation_unlimited/history.py", line 142, in muster
    data = history.get_significant_states(
  File "/usr/src/homeassistant/homeassistant/components/recorder/history.py", line 171, in get_significant_states
    return get_significant_states_with_session(
  File "/usr/src/homeassistant/homeassistant/components/recorder/history.py", line 288, in get_significant_states_with_session
    states = execute_stmt_lambda_element(
  File "/usr/src/homeassistant/homeassistant/components/recorder/util.py", line 188, in execute_stmt_lambda_element
    executed = session.execute(stmt)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1711, in execute
    conn = self._connection_for_bind(bind)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1552, in _connection_for_bind
    return self._transaction._connection_for_bind(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 747, in _connection_for_bind
    conn = bind.connect()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/future/engine.py", line 406, in connect
    return super(Engine, self).connect()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3234, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3313, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3280, in _wrap_pool_connect
    return fn()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 382, in connect
    return _ConnectionFairy._checkout(self, self._fairy)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 868, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 476, in checkout
    rec = pool._do_get()
  File "/usr/src/homeassistant/homeassistant/components/recorder/pool.py", line 75, in _do_get
    check_loop(
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 168, in check_loop
    raise RuntimeError(
RuntimeError: Blocking calls must be done in the executor or a separate thread; Use homeassistant.components.recorder.get_instance(hass).async_add_executor_job(); at homeassistant/components/recorder/pool.py, line 75: check_loop(
```

**Comment by sohnvonoff** [comment]
Hi, 
I have the problem too.

**Comment by ielbury** [comment]
Hey Robert, my apologies for being presumptuous. I installed the latest a greatest from GitHub and all seems to work fine.

Just have to say, awesome product you have developed here and many thanks!

**Comment by bassguitarist** [comment]
Hi Robert.
I confirm too that using the repository files, everything is working as expected.
Thanks
Simone

**Comment by korbendallas78** [comment]
Same problem here

**Comment by sohnvonoff** [comment]
Updated  _/config/custom_components/irrigation_unlimited_ from repo and deleted _"\_pycache\_"_. OK - again after HA restart.
Many Thanks

**Comment by HerveLeMen** [comment]
+1 a huge Thanks !

**Comment by korbendallas78** [comment]
> Updated _/config/custom_components/irrigation_unlimited_ from repo and deleted _"_pycache_"_. OK - again after HA restart. Many Thanks

If I delete _pycache, can't restart HA because config file error. Not found irrigation unlimited

**Comment by dmaciaszek** [comment]
Same problem.

**Comment by rgc99** [comment]
It is now officially released as 2022.6.0. Should come through soon via HACS.

This following is text from the release notes about a config file error. It would be better to correct the `zone_id:` _before_ updating.

If you get a configuration error after upgrading then check any `zone_id:` in the config. The id must conform to 'snake_case' style with the exception the first character _can_ be a number. This means only lower case, numbers and the underscore characters can be used. It cannot start or end with an underscore and no more than one together. Valid id's are `my_garden`, `front_lawn`, `rose_bed`, `1`. Some invalid examples are `Front_Lawn`, `front__lawn`, `_front_lawn`. You should have been getting warning messages in the previous release but now it is enforced. There is a good reason for this to be explained later but I thank you for your understanding in the meantime.

Wasn't supposed to be this way but got caught between a rock and a hard place.

**Comment by miguelpucela** [comment]
Everything seems to be working great after update.

Thanks!

**Comment by johnnysmithy852456** [comment]
After the update the logs seem ok but i still have schdule: index:null name:null

```
2022-06-07 16:23:48 WARNING (SyncWorker_6) [homeassistant.loader] We found a custom integration irrigation_unlimited which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-06-07 16:23:56 INFO (MainThread) [homeassistant.bootstrap] Setting up stage 2: {'input_datetime', 'automation', 'sensor', 'energy', 'scheduler', 'script', 'irrigation_unlimited', 'history', 'map', 'wled', 'mqtt', 'esphome', 'bureau_of_meteorology', 'input_number', 'input_text', 'reolink_dev', 'ffmpeg', 'radio_browser', 'spotify', 'system_health', 'scene', 'dlna_dms', 'dlna_dmr', 'ipp', 'switch', 'zone', 'cast', 'roku', 'pi_hole', 'group', 'tts', 'input_select', 'media_source', 'hacs', 'default_config', 'input_button', 'persistent_notification', 'sun', 'pyscript', 'nut', 'tag', 'calendar', 'apple_tv', 'shelly', 'meater', 'counter', 'input_boolean', 'device_tracker', 'timer', 'ios', 'application_credentials', 'panel_iframe', 'panasonic_viera', 'binary_sensor', 'momentary', 'mjpeg', 'my', 'utility_meter', 'logbook', 'mobile_app', 'trace', 'blueprint', 'homekit', 'sma'}
2022-06-07 16:23:59 INFO (MainThread) [homeassistant.setup] Setting up irrigation_unlimited
2022-06-07 16:23:59 INFO (MainThread) [custom_components.irrigation_unlimited]
Irrigation Unlimited
https://github.com/rgc99/irrigation_unlimited/issues
2022-06-07 16:23:59 DEBUG (MainThread) [custom_components.irrigation_unlimited] LOAD
2022-06-07 16:23:59 DEBUG (MainThread) [custom_components.irrigation_unlimited] REGISTER [2022-06-07 16:23:58] controller: 0, zone: 0, entity: irrigation_unlimited.coordinator
2022-06-07 16:23:59 DEBUG (MainThread) [custom_components.irrigation_unlimited] CALL [2022-06-07 16:23:58] service: adjust_time, controller: 1, zone: 1, data: {"percentage": 36.0}
2022-06-07 16:23:59 DEBUG (MainThread) [custom_components.irrigation_unlimited] CALL [2022-06-07 16:23:58] service: adjust_time, controller: 1, zone: 2, data: {"percentage": 36.0}
2022-06-07 16:23:59 DEBUG (MainThread) [custom_components.irrigation_unlimited] CALL [2022-06-07 16:23:58] service: adjust_time, controller: 1, zone: 3, data: {"percentage": 36.0}
2022-06-07 16:24:00 DEBUG (MainThread) [custom_components.irrigation_unlimited] START
2022-06-07 16:24:00 INFO (MainThread) [homeassistant.setup] Setup of domain irrigation_unlimited took 1.3 seconds
2022-06-07 16:24:00 INFO (MainThread) [homeassistant.components.binary_sensor] Setting up binary_sensor.irrigation_unlimited
2022-06-07 16:24:01 DEBUG (MainThread) [custom_components.irrigation_unlimited] REGISTER [2022-06-07 16:24:00] controller: 1, zone: 0, entity: binary_sensor.irrigation_unlimited_c1_m
2022-06-07 16:24:01 DEBUG (MainThread) [custom_components.irrigation_unlimited] REGISTER [2022-06-07 16:24:00] controller: 1, zone: 1, entity: binary_sensor.irrigation_unlimited_c1_z1
2022-06-07 16:24:01 DEBUG (MainThread) [custom_components.irrigation_unlimited] REGISTER [2022-06-07 16:24:00] controller: 1, zone: 2, entity: binary_sensor.irrigation_unlimited_c1_z2
2022-06-07 16:24:01 DEBUG (MainThread) [custom_components.irrigation_unlimited] REGISTER [2022-06-07 16:24:00] controller: 1, zone: 3, entity: binary_sensor.irrigation_unlimited_c1_z3
2022-06-07 16:24:01 INFO (MainThread) [custom_components.pyscript.global_ctx] Loaded /config/pyscript/irrigation_unlimited_service_shim.py
2022-06-07 16:25:12 INFO (MainThread) [homeassistant.components.automation.irrigation_unlimited_adjustment] Initialized trigger Irrigation Unlimited Adjustment
2022-06-07 16:25:12 INFO (MainThread) [homeassistant.components.automation.irrigation_unlimited_load_ui_controls] Irrigation Unlimited Load UI Controls: Running automation actions
2022-06-07 16:25:12 INFO (MainThread) [homeassistant.components.automation.irrigation_unlimited_load_ui_controls] Irrigation Unlimited Load UI Controls: Executing step call service
2022-06-07 16:25:12 INFO (MainThread) [homeassistant.components.automation.irrigation_unlimited_load_ui_controls] Initialized trigger Irrigation Unlimited Load UI Controls
2022-06-07 16:25:13 DEBUG (MainThread) [custom_components.irrigation_unlimited] INITIALISED
2022-06-07 16:25:13 INFO (MainThread) [homeassistant.components.automation.irrigation_unlimited_load_ui_controls] Irrigation Unlimited Load UI Controls: Executing step call service
2022-06-07 16:25:14 INFO (MainThread) [homeassistant.components.automation.irrigation_unlimited_adjustment] Irrigation Unlimited Adjustment: Running automation actions
2022-06-07 16:25:14 INFO (MainThread) [homeassistant.components.automation.irrigation_unlimited_adjustment] Irrigation Unlimited Adjustment: Executing step call service
```
