### ISSUE TITLE
error to restart hassio

### ISSUE THREAD

**Issue by riddik14** [rgc99/irrigation_unlimited#96]
when i restart hassio in log i receive this error

'''
2022-12-15 16:53:46.434 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/irrigation_unlimited/history.py", line 103, in _async_handle_refresh_event
    await self._async_update_history(self._stime)
  File "/config/custom_components/irrigation_unlimited/history.py", line 196, in _async_update_history
    data = await get_instance(self._hass).async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/recorder/history.py", line 167, in get_significant_states
    with session_scope(hass=hass) as session:
  File "/usr/local/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/usr/src/homeassistant/homeassistant/components/recorder/util.py", line 93, in session_scope
    session = get_instance(hass).get_session()
  File "/usr/src/homeassistant/homeassistant/components/recorder/core.py", line 244, in get_session
    raise RuntimeError("The database connection has not been established")
RuntimeError: The database connection has not been established
2022-12-15 16:53:46.459 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/history_stats/coordinator.py", line 87, in _async_update_from_event
    self.async_set_updated_data(await self._history_stats.async_update(event))
  File "/usr/src/homeassistant/homeassistant/components/history_stats/data.py", line 125, in async_update
    await self._async_history_from_db(current_period_start, current_period_end)
  File "/usr/src/homeassistant/homeassistant/components/history_stats/data.py", line 143, in _async_history_from_db
    states = await instance.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/history_stats/data.py", line 156, in _state_changes_during_period
    return history.state_changes_during_period(
  File "/usr/src/homeassistant/homeassistant/components/recorder/history.py", line 380, in state_changes_during_period
    with session_scope(hass=hass) as session:
  File "/usr/local/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/usr/src/homeassistant/homeassistant/components/recorder/util.py", line 93, in session_scope
    session = get_instance(hass).get_session()
  File "/usr/src/homeassistant/homeassistant/components/recorder/core.py", line 244, in get_session
    raise RuntimeError("The database connection has not been established")
RuntimeError: The database connection has not been established
'''

**Comment by rgc99** [comment]
The latest release was missing a requirement and therefore did not load properly. Will re-release shortly.
